spring.application.name=user-service

spring.config.import=optional:configserver:http://localhost:8888

spring.kafka.bootstrap-servers=localhost:9092
management.endpoints.web.exposure.include=health,info,busrefresh,refresh